kind: Service
apiVersion: v1
metadata:
  name: example-nginx
spec:
  selector:
    app: example-nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
  labels:
    app: example-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-nginx
  template:
    metadata:
      labels:
        app: example-nginx
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: nginx
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
